/*
rh-trex Service API

rh-trex Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KindNameList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KindNameList{}

// KindNameList struct for KindNameList
type KindNameList struct {
	Kind  string     `json:"kind"`
	Page  int32      `json:"page"`
	Size  int32      `json:"size"`
	Total int32      `json:"total"`
	Items []KindName `json:"items"`
}

// NewKindNameList instantiates a new KindNameList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKindNameList(kind string, page int32, size int32, total int32, items []KindName) *KindNameList {
	this := KindNameList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewKindNameListWithDefaults instantiates a new KindNameList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKindNameListWithDefaults() *KindNameList {
	this := KindNameList{}
	return &this
}

// GetKind returns the Kind field value
func (o *KindNameList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *KindNameList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *KindNameList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *KindNameList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *KindNameList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *KindNameList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *KindNameList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *KindNameList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *KindNameList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *KindNameList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *KindNameList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *KindNameList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *KindNameList) GetItems() []KindName {
	if o == nil {
		var ret []KindName
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *KindNameList) GetItemsOk() ([]KindName, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *KindNameList) SetItems(v []KindName) {
	o.Items = v
}

func (o KindNameList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KindNameList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableKindNameList struct {
	value *KindNameList
	isSet bool
}

func (v NullableKindNameList) Get() *KindNameList {
	return v.value
}

func (v *NullableKindNameList) Set(val *KindNameList) {
	v.value = val
	v.isSet = true
}

func (v NullableKindNameList) IsSet() bool {
	return v.isSet
}

func (v *NullableKindNameList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindNameList(val *KindNameList) *NullableKindNameList {
	return &NullableKindNameList{value: val, isSet: true}
}

func (v NullableKindNameList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindNameList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
