/*
rh-trex Service API

rh-trex Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KindNamePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KindNamePatchRequest{}

// KindNamePatchRequest struct for KindNamePatchRequest
type KindNamePatchRequest struct {
	Foo *string `json:"foo,omitempty"`
}

// NewKindNamePatchRequest instantiates a new KindNamePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKindNamePatchRequest() *KindNamePatchRequest {
	this := KindNamePatchRequest{}
	return &this
}

// NewKindNamePatchRequestWithDefaults instantiates a new KindNamePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKindNamePatchRequestWithDefaults() *KindNamePatchRequest {
	this := KindNamePatchRequest{}
	return &this
}

// GetFoo returns the Foo field value if set, zero value otherwise.
func (o *KindNamePatchRequest) GetFoo() string {
	if o == nil || IsNil(o.Foo) {
		var ret string
		return ret
	}
	return *o.Foo
}

// GetFooOk returns a tuple with the Foo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KindNamePatchRequest) GetFooOk() (*string, bool) {
	if o == nil || IsNil(o.Foo) {
		return nil, false
	}
	return o.Foo, true
}

// HasFoo returns a boolean if a field has been set.
func (o *KindNamePatchRequest) HasFoo() bool {
	if o != nil && !IsNil(o.Foo) {
		return true
	}

	return false
}

// SetFoo gets a reference to the given string and assigns it to the Foo field.
func (o *KindNamePatchRequest) SetFoo(v string) {
	o.Foo = &v
}

func (o KindNamePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KindNamePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Foo) {
		toSerialize["foo"] = o.Foo
	}
	return toSerialize, nil
}

type NullableKindNamePatchRequest struct {
	value *KindNamePatchRequest
	isSet bool
}

func (v NullableKindNamePatchRequest) Get() *KindNamePatchRequest {
	return v.value
}

func (v *NullableKindNamePatchRequest) Set(val *KindNamePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKindNamePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKindNamePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindNamePatchRequest(val *KindNamePatchRequest) *NullableKindNamePatchRequest {
	return &NullableKindNamePatchRequest{value: val, isSet: true}
}

func (v NullableKindNamePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindNamePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
