/*
rh-trex Service API

rh-trex Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KindNameListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KindNameListAllOf{}

// KindNameListAllOf struct for KindNameListAllOf
type KindNameListAllOf struct {
	Items []KindName `json:"items,omitempty"`
}

// NewKindNameListAllOf instantiates a new KindNameListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKindNameListAllOf() *KindNameListAllOf {
	this := KindNameListAllOf{}
	return &this
}

// NewKindNameListAllOfWithDefaults instantiates a new KindNameListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKindNameListAllOfWithDefaults() *KindNameListAllOf {
	this := KindNameListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *KindNameListAllOf) GetItems() []KindName {
	if o == nil || IsNil(o.Items) {
		var ret []KindName
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KindNameListAllOf) GetItemsOk() ([]KindName, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *KindNameListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []KindName and assigns it to the Items field.
func (o *KindNameListAllOf) SetItems(v []KindName) {
	o.Items = v
}

func (o KindNameListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KindNameListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableKindNameListAllOf struct {
	value *KindNameListAllOf
	isSet bool
}

func (v NullableKindNameListAllOf) Get() *KindNameListAllOf {
	return v.value
}

func (v *NullableKindNameListAllOf) Set(val *KindNameListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableKindNameListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableKindNameListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKindNameListAllOf(val *KindNameListAllOf) *NullableKindNameListAllOf {
	return &NullableKindNameListAllOf{value: val, isSet: true}
}

func (v NullableKindNameListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKindNameListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
